name: Go Release

on:
  release:
    types: [ published ]

jobs:

  release:
    name: Build with go ${{ matrix.go_version }} on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go_version: [ 1.16 ]
        os: [ ubuntu-latest ]

    steps:

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: |
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags "-s -w" -o timing-clock-in-dingding-linux-amd64 .
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -ldflags "-s -w" -o timing-clock-in-dingding-win-amd64.exe .
          CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -ldflags "-s -w" -o timing-clock-in-dingding-darwin-amd64 .


      - name: Gzip
        run: |
          tar -czvf timing-clock-in-dingding-linux-amd64.tar.gz timing-clock-in-dingding-linux-amd64
          tar -czvf timing-clock-in-dingding-win-amd64.tar.gz timing-clock-in-dingding-win-amd64.exe
          tar -czvf timing-clock-in-dingding-darwin-amd64.tar.gz timing-clock-in-dingding-darwin-amd64

      - name: Upload timing-clock-in-dingding-linux-amd64.tar.gz to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: timing-clock-in-dingding-linux-amd64.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload timing-clock-in-dingding-win-amd64.tar.gz to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: timing-clock-in-dingding-win-amd64.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload timing-clock-in-dingding-darwin-amd64.tar.gz to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: timing-clock-in-dingding-darwin-amd64.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}