name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags "-s -w" -o timming-clock-in-dingding-linux-amd64 . \
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -ldflags "-s -w" -o timming-clock-in-dingding-win-amd64.exe . \
          CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -ldflags "-s -w" -o timming-clock-in-dingding-darwin-amd64 .

